name: Check code style
on:
  - push
  - pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: npm ci
      - run: npm run test
      - run: npm run lint
      - run: npm run check
